const data = [
  {
    theaters: [
      {
        id: '1230',
        name: 'Centerplex Shopping Pátio Maceió',
        rooms: [
          {
            name: 'Sala 1',
            type: null,
            sessions: [
              {
                id: '69617156',
                price: 14.77,
                room: 'Sala 1',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                time: '18:00',
                defaultSector: '582566',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69617156/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69617158',
                price: 14.77,
                room: 'Sala 1',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T20:45:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:45',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T20:45:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:45',
                  year: '2022',
                },
                time: '20:45',
                defaultSector: '582566',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69617158/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 4',
            type: null,
            sessions: [
              {
                id: '69617155',
                price: 14.77,
                room: 'Sala 4',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T19:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T19:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:00',
                  year: '2022',
                },
                time: '19:00',
                defaultSector: '582531',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69617155/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69617193',
                price: 14.77,
                room: 'Sala 4',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T21:45:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:45',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T21:45:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:45',
                  year: '2022',
                },
                time: '21:45',
                defaultSector: '582531',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69617193/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
        ],
      },
      {
        id: '1568',
        name: 'CinePremium Cinemas',
        rooms: [
          {
            name: 'Sala 1',
            type: null,
            sessions: [
              {
                id: '69623851',
                price: 13.68,
                room: 'Sala 1',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                time: '18:00',
                defaultSector: '4603975',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69623851/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69623849',
                price: 13.68,
                room: 'Sala 1',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T20:20:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:20',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T20:20:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:20',
                  year: '2022',
                },
                time: '20:20',
                defaultSector: '4603975',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69623849/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 1',
            type: null,
            sessions: [
              {
                id: '69623850',
                price: 13.68,
                room: 'Sala 1',
                type: ['Legendado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T22:40:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '22:40',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T22:40:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '22:40',
                  year: '2022',
                },
                time: '22:40',
                defaultSector: '4603975',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69623850/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
        ],
      },
      {
        id: '1162',
        name: 'Cinesystem Maceió',
        rooms: [
          {
            name: 'Sala 2',
            type: null,
            sessions: [
              {
                id: '69622762',
                price: 50.16,
                room: 'Sala 2',
                type: ['Legendado', 'CINEPIC'],
                types: [
                  {
                    id: 2048,
                    name: 'CINEPIC',
                    alias: 'Cinépic',
                    display: true,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                time: '18:00',
                defaultSector: '4608803',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622762/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622679',
                price: 50.16,
                room: 'Sala 2',
                type: ['Legendado', 'CINEPIC'],
                types: [
                  {
                    id: 2048,
                    name: 'CINEPIC',
                    alias: 'Cinépic',
                    display: true,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T20:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:30',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T20:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:30',
                  year: '2022',
                },
                time: '20:30',
                defaultSector: '4608803',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622679/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 3',
            type: null,
            sessions: [
              {
                id: '69622593',
                price: 45.6,
                room: 'Sala 3',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T19:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T19:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:00',
                  year: '2022',
                },
                time: '19:00',
                defaultSector: '4715822',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622593/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622624',
                price: 45.6,
                room: 'Sala 3',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T21:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:30',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T21:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:30',
                  year: '2022',
                },
                time: '21:30',
                defaultSector: '4715822',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622624/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 8',
            type: null,
            sessions: [
              {
                id: '69622830',
                price: 45.6,
                room: 'Sala 8',
                type: ['Legendado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T19:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:30',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T19:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:30',
                  year: '2022',
                },
                time: '19:30',
                defaultSector: '4715823',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622830/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 9',
            type: null,
            sessions: [
              {
                id: '69622582',
                price: 45.6,
                room: 'Sala 9',
                type: ['Legendado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:30',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:30',
                  year: '2022',
                },
                time: '18:30',
                defaultSector: '4608799',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622582/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622803',
                price: 45.6,
                room: 'Sala 9',
                type: ['Legendado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T21:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T21:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:00',
                  year: '2022',
                },
                time: '21:00',
                defaultSector: '4608799',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622803/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
        ],
      },
      {
        id: '924',
        name: 'Kinoplex Maceió',
        rooms: [
          {
            name: 'Sala 1',
            type: null,
            sessions: [
              {
                id: '69622519',
                price: 43.32,
                room: 'Sala 1',
                type: ['Legendado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:30',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:30',
                  year: '2022',
                },
                time: '18:30',
                defaultSector: '4608850',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622519/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622517',
                price: 43.32,
                room: 'Sala 1',
                type: ['Legendado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Legendado',
                    alias: 'LEG',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T21:05:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:05',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T21:05:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:05',
                  year: '2022',
                },
                time: '21:05',
                defaultSector: '4608850',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622517/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 2',
            type: null,
            sessions: [
              {
                id: '69622516',
                price: 43.32,
                room: 'Sala 2',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:10:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:10',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:10:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:10',
                  year: '2022',
                },
                time: '18:10',
                defaultSector: '4608849',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622516/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622526',
                price: 43.32,
                room: 'Sala 2',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T20:50:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:50',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T20:50:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:50',
                  year: '2022',
                },
                time: '20:50',
                defaultSector: '4608849',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622526/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 3',
            type: null,
            sessions: [
              {
                id: '69622520',
                price: 43.32,
                room: 'Sala 3',
                type: ['Dublado', 'KinoEvolution'],
                types: [
                  {
                    id: 512,
                    name: 'KinoEvolution',
                    alias: 'KinoEvolution',
                    display: true,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:00',
                  year: '2022',
                },
                time: '18:00',
                defaultSector: '4608847',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622520/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622528',
                price: 43.32,
                room: 'Sala 3',
                type: ['Dublado', 'KinoEvolution'],
                types: [
                  {
                    id: 512,
                    name: 'KinoEvolution',
                    alias: 'KinoEvolution',
                    display: true,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T20:35:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:35',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T20:35:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '20:35',
                  year: '2022',
                },
                time: '20:35',
                defaultSector: '4608847',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622528/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 4',
            type: null,
            sessions: [
              {
                id: '69665733',
                price: 31.92,
                room: 'Sala 4',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T19:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:00',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T19:00:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '19:00',
                  year: '2022',
                },
                time: '19:00',
                defaultSector: '4608848',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69665733/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69665721',
                price: 31.92,
                room: 'Sala 4',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T21:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:30',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T21:30:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:30',
                  year: '2022',
                },
                time: '21:30',
                defaultSector: '4608848',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69665721/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
          {
            name: 'Sala 6',
            type: null,
            sessions: [
              {
                id: '69622513',
                price: 43.32,
                room: 'Sala 6',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T18:45:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:45',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T18:45:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '18:45',
                  year: '2022',
                },
                time: '18:45',
                defaultSector: '4608846',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622513/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
              {
                id: '69622527',
                price: 43.32,
                room: 'Sala 6',
                type: ['Dublado', 'Normal'],
                types: [
                  {
                    id: 1,
                    name: 'Normal',
                    alias: '2D',
                    display: false,
                  },
                  {
                    id: 0,
                    name: 'Dublado',
                    alias: 'DUB',
                    display: true,
                  },
                ],
                date: {
                  localDate: '2022-10-19T21:15:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:15',
                  year: '2022',
                },
                realDate: {
                  localDate: '2022-10-19T21:15:00-03:00',
                  isToday: false,
                  dayOfWeek: 'quarta-feira',
                  dayAndMonth: '19/10',
                  hour: '21:15',
                  year: '2022',
                },
                time: '21:15',
                defaultSector: '4608846',
                midnightMessage: null,
                siteURL:
                  'https://carrinho.ingresso.com/checkout/#/adicionar/69622527/home',
                nationalSiteURL: null,
                hasSeatSelection: true,
                driveIn: false,
                streaming: false,
                maxTicketsPerCar: 0,
                enabled: true,
                blockMessage: '',
              },
            ],
          },
        ],
      },
    ],
    date: '2022-10-19',
    dateFormatted: '19/10',
    dayOfWeek: 'quarta-feira',
  },
];

function filterSession(session) {
  const { time, types } = session;
  return {
    time,
    types: types.map((i) => i.alias),
  };
}

function filterRoom(room) {
  const { sessions, name } = room;
  return {
    name,
    sessions: sessions.map(filterSession),
  };
}

function filterTheater(theater) {
  const { name, rooms } = theater;
  return {
    name,
    rooms: rooms.map(filterRoom),
  };
}

const finalData = data.map((t) => {
  const { date, dateFormatted, theaters } = t;
  return {
    date,
    dateFormatted,
    theaters: theaters.map(filterTheater),
  };
});

const description = finalData[0].theaters.map((theater) => {
  const { rooms } = theater;
  const roomStr = rooms.map((room) => {
    const { sessions } = room;

    return [
      room.name,
      sessions
        .map((session) => `[${session.types[1]}] ${session.time}`)
        .join(' | '),
    ].join(' - ');
  });

  const theaterStr = [theater.name, roomStr, null];
  return theaterStr.flat();
});

description.flat().join('\n');
